version: '2.3'
services:
  xl-deploy:
    build: docker/xl-deploy
    ports:
    - "4516:4516"
    environment:
    - ADMIN_PASSWORD=admin

  xl-release:
    build: docker/xl-release
    ports:
    - "5516:5516"
    depends_on:
    - xl-deploy
    environment:
    - ADMIN_PASSWORD=admin

  xl-cli:
    build: docker/xl-cli
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "--xl-deploy-url", "http://xl-deploy:4516/", "--xl-release-url", "http://xl-release:5516/", "-f", "/data/docker/xl-cli/configure-xl-devops-platform.yaml"]
    volumes:
    - .:/data:ro

  dockerproxy: # warning: this potentially opens up a security hole. Make sure you use a firewall and do not accept network connections to your computer.
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONTAINERS=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - SECRETS=1
      - SERVICES=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1
